stages:
- build
- deploy
- release

variables:
    FACTORY_PRODUCT_NAME: qgis_logger
    FACTORY_PACKAGE_NAME: qgis_logger
    FACTORY_PACKAGE_TYPE: plugin
    FACTORY_MANIFEST: ".lizcloud/factory.manifest"

build:
  stage: build
  script:
    - make -C tests
    - make -C .lizcloud -f factory.mk package
  environment:
    name: snap
  artifacts:
    paths:
      - ".lizcloud/factory.manifest"
  tags:
    - infrav3

deploy_snap:
  stage: deploy
  script:
    - $FACTORY_SCRIPTS/deploy-package $FACTORY_PACKAGE_NAME
  environment:
    name: snap
  tags:
    - infrav3

release_prod:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release_package $FACTORY_PACKAGE_NAME
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - infrav3

build_legacy:
  stage: build
  script:
    - make -C .lizcloud -f fabric.mk package
  environment:
    name: snap
  tags:
    - fabric
    - infrav2

deploy_snap_legacy:
  stage: deploy
  script:
    - sudo -u fabric fab snap deploy:qgis3_logger,force=true
  environment:
    name: snap
  tags:
    - fabric
    - infrav2

release_prod_legacy:
  stage: release
  script:
    - sudo -u fabric fab prod release:qgis3_logger
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - fabric
    - infrav2

